### PR TITLE
SEP 19: Run salt-master as non-root user (unprivileged)

### PR DESCRIPTION
**Pull request by harmv**
as suggested in https://github.com/saltstack/salt/issues/55886  created a SEP for this issue.

### CODE REVIEW

**Comment by waynew** [comment]
This is SEP 19, feel free to update your PR 👍

**Comment by thatch45** [comment]
I completely agree with you that this should be fixed. But this SEP does not present a viable solution or a way to solve this issue. A SEP needs to evaluate what the blockers are to implement and present a path forward on how to resolve it.

This SEP is also abusive in the language used and should be presented in a more professional way.

**Comment by thatch45** [comment]
The main blocker right now is the configuration loading system, it statically looks for files that are only available to root. We should evaluate how that can either be fixed or if Salt's configuration loading system should be extracted from Salt or replaced so that we can create a re-usable system to bypass these issues.

The POP configuration system is designed to fix this problem and can be a source of consideration or could be enhanced so that it could be used and the configuration loading code could be simplified.

**Comment by waynew** [comment]
@harmv are you planning to update the text of your SEP with the feedback from Tom?

**Comment by harmv** [comment]
> @harmv are you planning to update the text of your SEP with the feedback from Tom?

I've updated the SEP with both remarks from Tom.

**Comment by waynew** [comment]
@harmv Thanks for updating this SEP. We've had some internal discussion on this and we absolutely support the fundamental idea (being able to run salt-master as non-root) - but there are a number of questions that are unasked and unanswered by the SEP in it's current form.

If you are willing to drive this SEP to completion, we'd like to have at least a few discussions about the broader implications behind this. We're planning to at least discuss it in a Community Open Hour, though we're also expecting to have a few more discussions. The change is definitely non-trivial. Is this something that you're interested in, or would you like to have someone else take over?

**Comment by The-Loeki** [comment]
As longtime salt user I'd love for this SEP to 'pass' ;) so I took a stab at furthering the discussion a bit.
Shall I submit a new PR for https://github.com/The-Loeki/salt-enhancement-proposals/blob/SEP-19/0019-master-non-root.md ?

**Comment by waynew** [comment]
@The-Loeki yeah, I think if you're willing to take on the reins, that would be 👍

**Comment by waynew** [comment]
@The-Loeki when you open your PR, if @harmv doesn't have any objections, you can just open it as SEP 19 again. For now I'll go ahead and close this PR.

**Pull request closed without merging**
